security:
    enable_authenticator_manager: true

    role_hierarchy:
        ROLE_ADMIN: [ROLE_WRITER, ROLE_SPELLCHECKER, ROLE_JOURNALIST]

    providers:
        in_memory:
            memory:
                users:
                    alice: { roles: ROLE_WRITER }
                    spellchecker: { roles: ROLE_SPELLCHECKER }
                    journalist: { roles: ROLE_JOURNALIST }
                    admin: { roles: ROLE_ADMIN }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/

            logout:
                target: /
            custom_authenticators:
                - App\Security\YoloAuthenticator
